### ISSUE TITLE
Does this work with hot module reloading?

### ISSUE THREAD

**Issue by Rillus** [react-toolbox/toolbox-loader#1]
From what I see ExtractTextPlugin doesn't like HMR.

Is this correct?

Currently my setup is thus:

```
{
    test: /\.(scss|css)$/, 
    include: /node_modules\/react-toolbox/, 
    loader: 'style-loader!css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]-[local]___[hash:base64:5]!sass-loader?sourceMap!toolbox-loader'
},
```

and it doesn't pick up the `toolboxTheme` at all...?

**Comment by javivelasco** [comment]
Yes, I've never got HMR working with live refreshing CSS but neither looked at the issue to try to get it working. Anyway, it's not actually a toolbox-loader issue since it's already telling webpack about the dependency with theme file (`this.addDependency(themePath)`).

If somebody get it working live reloading in the example project or toolbox project it would be very nice!
Closing here since I  think it's not related. @Rillus you can open an issue in the toolbox or example project if you want!
